### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by SN-18**
Added LICENSE file.

### CODE REVIEW

**Comment by pncnmnp** [comment]
I agree. MIT License certainly seems like a viable option for this repo. Furthermore, as this repo has more educational requirements, we don't need a stronger patent clause.

**Comment by rdeodha** [comment]
This change looks good to me, MIT is a viable option for our repo. Approving this pull request.

**Review by rdeodha — DISMISSED** [review]

**Review by rdeodha — COMMENTED** [review]
I believe this file should be LICENSE.md, instead it seems this file is only named LICENSE.

**Comment by SN-18** [comment]
@rdeodha after ownership changes for our repository, fork SN-18:main does not exist
So I can go ahead and merge this pull request and create another patch to fix the filename
Let me know what you think

**Comment by rdeodha** [comment]
Approving for now so that file can be renamed after the merge.

**Pull request merged**
